name = "CombOpt"
uuid = "73d28a3a-e55c-11e8-176c-fb35e7959d73"
authors = ["Dileep Kishore <k.dileep1994@gmail.com>"]
version = "0.2.0"

[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
